INSERT INTO dim_sectors (sector_id, naics_sector_code, sector_description) VALUES
(1, '11', 'Agriculture, Forestry, Fishing and Hunting'),
(2, '21', 'Mining, Quarrying, and Oil and Gas Extraction'),
(3, '22', 'Utilities'),
(4, '23', 'Construction'),
(5, '31', 'Manufacturing (31-33)'),
(6, '42', 'Wholesale Trade'),
(7, '44', 'Retail Trade (44-45)'),
(8, '48', 'Transportation and Warehousing (48-49)'),
(9, '51', 'Information'),
(10, '52', 'Finance and Insurance'),
(11, '53', 'Real Estate and Rental and Leasing'),
(12, '54', 'Professional, Scientific, and Technical Services'),
(13, '55', 'Management of Companies and Enterprises'),
(14, '56', 'Administrative and Support and Waste Management'),
(15, '61', 'Educational Services'),
(16, '62', 'Health Care and Social Assistance'),
(17, '71', 'Arts, Entertainment, and Recreation'),
(18, '72', 'Accommodation and Food Services'),
(19, '81', 'Other Services (except Public Administration)'),
(20, '92', 'Public Administration');